### ISSUE TITLE
Andrew's feedback June 23

### ISSUE THREAD

**Issue by andrewsalway** [CatalogueLegacies/antconc.github.io#26]
**Module 1, Introduction to AntConc:** Here and elsewhere I see a few typos/spellings and a couple of phrasings that sound awkward to me, but maybe these are still works in progress(?) and I'm not sure how to effectively communicate these (cf. suggested changes and Comments in Google Docs)

**Module 2, Importing Data:** "AntConc works only with plain text files with the file extension .txt" is misleading on two counts: (i) you can choose to view and hence open 'All files'; (ii) AntConc can process files containing markup e.g. HTML and XML. I guess the main point is that you can't process e.g. .docx or .pdf files and these would have to be converted to text files first.

**Module 5, Word Lists:** 
- I'm not sure what is meant by "minor variations in data values, e.g. names of people, organisations, places, classification terms". 
- Regarding case sensitivity - "because knowing where words are used in relation to punctuation is a tell for features like sentence structure and length" is a reason in our case, but there is a more general reason which also applies here, i.e. getting separate counts for e.g. 'cook' and 'Cook' (the name) etc.
- "Good practice when saving outputs" - perhaps suggest never use default name because you may overwrite previous results, plus some info about corpus, query and settings can be given in the filename.
- Would Task 2 be done better once sorting Concordance lines by words before and after the search term has been explained?

**Module 6, Search:**
- maybe add 'Concordances' to the title of the module?
- "a series of lines of text, known as ‘condordances’ " , I think the series of lines is a concordance, I would refer to each line as a 'concordance line'
- "It assumes we care more about the word next after the search term rather than before it." by default yes, but as noted further on there are options to sort by preceding words too (under 'Kwic Sort')

**Module 7, Collocates**
- "The absence of “the behind”, “a behind”, and “this behind” , do you actually see many "the|a|this posterior"? (I guess 'posterior' will mostly likely be preceded by personal possessive pronoun or a name).
- " to do this properly we need to know more about what the stat value means." Indeed, but I'm not sure there is general agreement in corpus linguistics about what can be inferred from collocation statistics - and to get into it requires quite some stats/maths.
- Maybe some of the tasks here could be done with sorted concordances rather than (or as well as) with collocation stats?

**Comment by drjwbaker** [comment]
Edits:

- [x] E2
- [x] E5
> Would Task 2 be done better once sorting Concordance lines by words before and after the search term has been explained?
- I take the point. I've made a note re the later episode, but haven't gone fully down the suggested route. I feel it is important to get used to a little interaction between tools without going into each in depth each time they are introduced. We'll see how this goes. 
- [x] E6
- [x] E7
> Maybe some of the tasks here could be done with sorted concordances rather than (or as well as) with collocation stats?
- park now and resolve after July training (with BL dataset) https://github.com/CatalogueLegacies/antconc.github.io/issues/27

**Comment by drjwbaker** [comment]
Many thanks @andrewsalway. I've integrated most suggestions, though one of these issues we'll take forward for post training.

On typos, if there is any egregious, you have direct edit power (all the episodes are at https://github.com/CatalogueLegacies/antconc.github.io/tree/gh-pages/_episodes). Though this isn't a big issue as these are only lessons for the initial test sessions: we'll be rewriting everything for the BL dataset after July.
