### ISSUE TITLE
Change to IAMS images dataset

### ISSUE THREAD

**Issue by drjwbaker** [CatalogueLegacies/antconc.github.io#29]
Based on July feedback: redevelop materials around IAMS images dataset.

- [x] Gather CC0 dataset
- [x] First scan of dataset
- [x] Clean dataset for use (use IAMS_selection3.txt)
- [x] Test existing tasks on dataset (@drjwbaker episode 6, @rossi-uk episode 5), and create new issues where substantive changes needed. To include:
	- [x] Episode 5
	- [x] Episode 6 https://github.com/CatalogueLegacies/antconc.github.io/issues/39
	- [x] Episode 7 https://github.com/CatalogueLegacies/antconc.github.io/issues/40
	- [x] Noting further reading on MDG as a different corpus with different characteristics, leading into Next Steps 1
	- [x] 'shewing' in quoted text: so linguistic analysis as means of seeing what is there (in this case, non-curv)
	- [x] ~how we reduced the corpus down from all data to subset (choice of ScopeConent; dirty remove of lists/subject headings; not remove quoted; down to around 1/4 of all ScopeContent text): simple descriptions + point to code/documentation~ Move to separate issue https://github.com/CatalogueLegacies/antconc.github.io/issues/42
	- [x] Open PR with ep1-4 revisions https://github.com/CatalogueLegacies/antconc.github.io/pull/41

**Comment by drjwbaker** [comment]
Will require preparation of dataset for use and publication.

**Comment by drjwbaker** [comment]
Breaking out from `Clean dataset for use` into sub-tasks:

- [x] import data into OpenRefine
	- use OpenRefine here as it gives me as greater sense of the data as I'm working with it.
- [x] deduplicate on ‘ScopeContent’ field
	- 113105 unique entries in 157910 records, suggesting duplicates.
	- facet by blank = false 150569, true 7341 
		- remove records with blank `ScopeContent` field (now 150569 records)
	- facet by duplicate = false 104696, true 45873
		- remove 6 duplicate rows in `.` only. (now 150562 records)
		- blank down to keep one of each duplicate and then remove blank rows (now 113104 records) [note this is 1 fewer than above as in the midst of this I removed white space]
- [x] edit ‘ScopeContent’  fields that start `Genre:` because the value after `Genre:` has been unsatisfactorily merged with the first word of the description, e.g.: "Genre: Ethnographical PhotographyFull-length standing profile portrait of a Yawyin man with his bow." or "Genre: Landscape PhotographyDistant view looking down onto the village from an elevated position, showing houses and surrounding rice terraces."
	- `value.replace("Photography", "Photography. ")` to make new column with correct data
- [x] export version of dataset containing `RecordId`, `Reference` and `ScopeContent` only, and sorted by `RecordId` for initial textual analysis. (on Drive)
- [x] create backup of OpenRefine activity history: [here](https://github.com/CatalogueLegacies/antconc.github.io/blob/gh-pages/data/BL/IAMS-openrefine-transformation.json)

**Comment by rossi-uk** [comment]
Note also "Genre: Fine Arts, Photography.  ofSide view of the gilded silver drinking vessel, made from a buffalo horn." The break is after 'of' which is preceded by full-stop then space

**Comment by drjwbaker** [comment]
One-pager on the dataset written up and in the Drive.

**Comment by drjwbaker** [comment]
Perhaps move to two datasets: one general BL, one India Arch subset.
Speaking to @andrewsalway 30 September to go through data.

**Comment by drjwbaker** [comment]
>       * [x]  'shewing' in quoted text: so linguistic analysis as means of seeing what is there (in this case, non-curv)

@rossi-uk I put this in ep5 at line 63 https://github.com/CatalogueLegacies/antconc.github.io/commit/7e45b226b41df82e945447479178a64f6b97b196 so ignore than when you get time to run through that episode
