### ISSUE TITLE
Searching Concordances - Searching in Antconc change

### ISSUE THREAD

**Issue by rossi-uk** [CatalogueLegacies/antconc.github.io#46]
Searching in Antconc last bullet point is not valid for IAMS data as one txt file. Remove or Point to alternative set?

**Comment by drjwbaker** [comment]
Which line here https://github.com/CatalogueLegacies/antconc.github.io/blob/gh-pages/_episodes/06-search.md are you referring to @rossi-uk?

**Comment by rossi-uk** [comment]
Last bullet point in Searching in Antconc section. 
For each line, it returns information on the file name from which the search term orginates. That is, whilst we’ve separated our file into parts to ease import and processing, you should be able to see there is comparative potential here.

**Comment by rossi-uk** [comment]
line 30

**Comment by drjwbaker** [comment]
Ah, good catch. I thought you meant the bottom of the page! Fixed now.
